name: Build & Publish to gh-pages

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Build dist
        run: npm run build
      - name: Prepare gh-pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          # Fetch existing gh-pages if it exists
          if git ls-remote --exit-code origin refs/heads/gh-pages; then
            git fetch origin gh-pages
            git checkout gh-pages
            # Remove everything (keep history)
            git rm -r . > /dev/null 2>&1 || true
          else
            git checkout --orphan gh-pages
            rm -rf *
          fi
          cp -R dist/* .
          touch .nojekyll
          echo "Last build: $(date -u +%Y-%m-%dT%H:%M:%SZ)" > build-info.txt
          git add .
          if git diff --cached --quiet; then
            echo "No changes to publish."; exit 0
          fi
          git commit -m "Publish dist (CI) $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          git push origin HEAD:gh-pages
      - name: Summary
        run: echo "Deployment complete. Set GitHub Pages to use gh-pages / root." 
